### ISSUE TITLE
Depreciation notice

### ISSUE THREAD

**Issue by krsibbald** [gbiczo/oxcelix#11]
I am receiving the following depreciation notice with ruby 2.5.1 
```gems/oxcelix-0.4.1/lib/oxcelix.rb:36: warning: constant ::Fixnum is deprecated```

It is due to a change made in ruby 2.4.0
https://bugs.ruby-lang.org/issues/12005
https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/

**Comment by roberts1000** [comment]
I'm seeing the same thing.

@gbiczo Are you open to considering a PR?

**Comment by gbiczo** [comment]
Hi All,

thanks a lot for pointing this out, and @krsibbald fo the PR.
Yes, plan is to fix this and some minor glitches in the gem soon, should be ready in a week or so.

**Comment by roberts1000** [comment]
Great.  Thank you!

**Comment by cmendla** [comment]
Have we gotten anywhere with this issue and https://github.com/gbiczo/oxcelix/pull/12  ?

**Comment by gbiczo** [comment]
Yeap, this has been fixed now, thanks for your patience! :)
