### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by roberts1000** [gbiczo/oxcelix#13]
@gbiczo Can you create a new release? It would be nice to have a full gem release, instead of having to pull master from GitHub, to correct the Fixnum issue.

(Also, a release tag was never created for 0.4.0.)

**Comment by doublephi** [comment]
@gbiczo I second this. Definitely need a new release for master. 0.4.1 does not have the Fixnum fix.

**Comment by gbiczo** [comment]
Hey all,

I'll try and release the new version this weekend

**Comment by doublephi** [comment]
@gbiczo Still looking for this release...

**Comment by gbiczo** [comment]
Hi all, sorry for the delay, the new version has been published now to rubygems.org.
Closing.
